const express = require('express');
const routes = express.Router();
const adminControllers = require('../controllers/admin');
const saeeControllers = require('../controllers/saee');
const adminMidellwares = require('../middlewares/admin');
routes.get('/', adminMidellwares.isAdmin, adminControllers.getIndex);
routes.get('/remove-store/:id', adminMidellwares.isAdmin, adminControllers.removeStore);
routes.post('/send-store-email/:id', adminMidellwares.isAdmin, adminControllers.sendStoreEmail);
routes.get('/change-saee-status', adminMidellwares.isAdmin, adminControllers.changeSaeeStatus);
routes.post('/edit-saee-prices', adminMidellwares.isAdmin, adminControllers.editSaeePrice);
routes.get('/login', adminControllers.getLogin);
routes.post('/login', adminControllers.postLogin);
module.exports = routes;