const express = require('express');
const routes = express.Router();
const adminControllers = require('../controllers/admin');
const saeeControllers = require('../controllers/saee');
routes.get('/', adminControllers.getIndex);
routes.get('/remove-store/:id', adminControllers.removeStore);
routes.post('/send-store-email/:id', adminControllers.sendStoreEmail);
routes.get('/change-saee-status', adminControllers.changeSaeeStatus);
routes.post('/edit-saee-prices', adminControllers.editSaeePrice);
module.exports = routes;